<a href="https://colab.research.google.com/github/JatinSharma222/AI-experiments-Univaersity/blob/main/Experiment7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment 7
Bayesian Learning with Bayes' Theorem and Naive Bayes Classifier



In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load dataset
file_path = '/content/seattle-weather.csv'
dataset = pd.read_csv(file_path)
dataset.head()

date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain

## Exploratory Data Analysis
Inspect the dataset structure and statistics.

In [2]:
# Display dataset information
dataset.info()

# Display summary statistics
dataset.describe()

# Check for missing values
dataset.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           1461 non-null   object 
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object 
dtypes: float64(4), object(2)
memory usage: 68.6+ KB


date             0
precipitation    0
temp_max         0
temp_min         0
wind             0
weather          0
dtype: int64

## Data Preprocessing
We will:
1. Drop irrelevant columns (e.g., `date`).
2. Convert the target variable (`weather`) to numerical labels.

In [3]:
# Drop the `date` column
dataset.drop(columns=['date'], inplace=True)

# Encode the target variable
dataset['weather'] = dataset['weather'].astype('category').cat.codes

# Display the processed dataset
dataset.head()

precipitation  temp_max  temp_min  wind  weather
0            0.0      12.8       5.0   4.7        0
1           10.9      10.6       2.8   4.5        2
2            0.8      11.7       7.2   2.3        2
3           20.3      12.2       5.6   4.7        2
4            1.3       8.9       2.8   6.1        2

## Bayesian Learning Using Bayes' Theorem
We compute the posterior probability for one example.

In [4]:
# Example: Compute the posterior probability of a specific weather condition
def bayes_theorem(prior, likelihood, evidence):
    return (prior * likelihood) / evidence

# Example values (to be replaced with real values from the dataset)
prior = 0.3  # Prior probability of a weather condition
likelihood = 0.8  # Likelihood of the observed data given the weather condition
evidence = 0.5  # Probability of the observed data
posterior = bayes_theorem(prior, likelihood, evidence)
print(f"Posterior Probability: {posterior}")

Posterior Probability: 0.48


## Naive Bayes Classifier
We will split the dataset into training and testing sets, train a Naive Bayes classifier, and evaluate its performance.

In [5]:
# Split the dataset into features and target variable
X = dataset.drop(columns=['weather'])
y = dataset['weather']

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the Naive Bayes Classifier
nb = GaussianNB()
nb.fit(X_train, y_train)

# Make predictions
y_pred = nb.predict(X_test)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.8293515358361775

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         9
           1       0.00      0.00      0.00        25
           2       0.96      0.91      0.94       120
           3       0.57      0.50      0.53         8
           4       0.76      0.99      0.86       131

    accuracy                           0.83       293
   macro avg       0.46      0.48      0.47       293
weighted avg       0.75      0.83      0.78       293


Confusion Matrix:
 [[  0   0   0   0   9]
 [  1   0   0   0  24]
 [  0   0 109   3   8]
 [  0   0   4   4   0]
 [  1   0   0   0 130]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
